import { Box, Flex } from "@chakra-ui/react";
import Hero from "../utils/Hero";

const Main = (props) => {
  return (
    <Box height="500px" px={{ base: 4 }} {...props}>
      kontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontolkontol
    </Box>
  );
};

export default Main;
